services:

  nginx:
    build:
      context: ../srcs/services/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - /home/lbastien/data/wp_files:/var/www/html
      - /home/lbastien/data/ssl:/etc/ssl
    networks:
      - internal
#    restart: always
    depends_on:
      - php

  php:
    env_file: ".env"
    build:
      context: ../srcs/services/php
      dockerfile: Dockerfile
    volumes:
      - /home/lbastien/data/wp_files:/var/www/html
    networks:
      - internal
#    restart: always
    depends_on:
      - mariadb

  mariadb:
    env_file: ".env"
    build:
      context: ../srcs/services/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/lbastien/data/database:/var/lib/mysql
    networks:
      - internal
#    restart: always

networks:
  internal:
    driver: bridge
