services:

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "4242:443"
    volumes:
      - ../data/wordpress-files:/var/www/html
      - ../data/logs/nginx:/var/log/nginx
    networks:
      - internal

  php:
    env_file: ".env"
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ../data/wordpress-files:/var/www/html
    networks:
      - internal

  mariadb:
    env_file: ".env"
    build:
      context: ./services/mariadb
      dockerfile: Dockerfile
    volumes:
      - ../data/database:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
