services:

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../data/static:/var/www/html
    networks:
      - internal

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    networks:
      - internal


networks:
  internal:
    driver: bridge
