services:

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../data/content:/var/www/html
      - ../data/logs/nginx:/var/log/nginx
    networks:
      - internal

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ../data/content:/var/www/html
    networks:
      - internal


networks:
  internal:
    driver: bridge
