services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../data/static:/usr/share/nginx/html

networks:
  main_network:
    driver: bridge
