services:

  nginx:
    build:
      context: ../srcs/services/nginx
      dockerfile: Dockerfile
    ports:
      - "4242:443"
    volumes:
      - ../data/wp_files:/var/www/html
    networks:
      - internal

  php:
    env_file: ".env"
    build:
      context: ../srcs/services/php
      dockerfile: Dockerfile
    volumes:
      - ../data/wp_files:/var/www/html
    networks:
      - internal

  mariadb:
    env_file: ".env"
    build:
      context: ../srcs/services/mariadb
      dockerfile: Dockerfile
    volumes:
      - ../data/database:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
