version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      -static_site:/usr/share/nginx/html

volumes:
  static_site: ../data/static